### ISSUE TITLE
支持mongodb吗

### ISSUE THREAD

**Issue by cuijianguo** [easysql/easy_sql#10]

**Comment by gmlove** [comment]
mongodb现在还不支持sql查询，所以没法直接直接mongodb做后端引擎。

不过，一般比较少选择mongodb做数仓。

常见的做法是：
- 将mongodb的数据接入到hdfs，存储为Json格式
- 用hive里面用json函数取各类字段完成ETL开发

**Comment by gmlove** [comment]
no new activity
