### ISSUE TITLE
ci proposal: introduce mergify bot

### ISSUE THREAD

**Issue by Fedomn** [easysql/easy_sql#19]
Currently, our PR merge process is manually triggered, which means we need to focus on many repetitive tasks such as merging squashes, deleting pr branches, checking PR titles, etc.

How about introducing [mergify bot](https://docs.mergify.com/getting-started/#installation) to reduce the above repetitive work?

After introducing mergify bot, we could add a `can-merge` label on PR or `Approve` PR in `Review changes` pane, and then the bot helps us to merge PR and something else misc work.

References that can work: https://github.com/Fedomn/sql-query-engine-rs/pull/36

**Comment by gmlove** [comment]
Great suggestion! Let's investigate on this.
